steps:
  - name: ":node: Yarny"
    command: yarn install --frozen-lockfile
    plugins:
      - docker-compose#v2.5.1:
          run: app  
          config: docker-compose.yml
  - name: "validate formatting"
    command: make prettier
    plugins:
      - docker-compose#v2.5.1:
          run: app  
          config: docker-compose.yml