steps:
  - name: ":node: Yarny - doing up styles"
    command: 
      - "cd dev/"
      - "yarn install --frozen-lockfile"
      - "npm run badger"
      - "make prettier"
      - "make lint"
      - "make flow"
      - "../cc-test-reporter before-build"
      - "make test-coverage"
      - "../cc-test-reporter after-build --exit-code 0"
    plugins:
      - docker-compose#v2.5.1:
          run: app  
          config: docker-compose.yml
  - name: "part 2 :hammer:"
    command: 
      - "ls"
    plugins:
      - docker-compose#v2.5.1:
          run: app  
          config: docker-compose.yml